### PR TITLE
libretro: Add gearboy_libretro.info

### PR DESCRIPTION
**Pull request by orbea**
These info files are required for proper operation of the libretro core. It is customary to host these in the libretro-super repo to make them easy to maintain, but given that the libretro code was merged in this repo and this repo also maintains release tags it would be useful to have the gearboy_libretro.info file provided in those release tarballs for distro packages. I suspect this file will not need to be updated often, but if it does the downside is that it will need to be updated in two repos.

Also please see https://github.com/libretro/libretro-super/pull/653 and https://github.com/libretro/libretro-super/tree/master/dist/info.

Can you please make sure the details in the info file are correct? Also can Gearboy use a bios file? I could not find any info indicating so, but maybe I missed it?

### CODE REVIEW

**Comment by hyarsan** [comment]
Umm, didn't I provide a core info file over on https://github.com/drhelius/Gearboy/issues/52 ? Oh well...

**Comment by drhelius** [comment]
Thanks. 
Gearboy can use bios files but it doesn't need any bios to work.
They bios is included, something I'm going to remove now.

**Comment by hyarsan** [comment]
The core file is not perfect: https://github.com/libretro/libretro-super/pull/655/commits/44bae2ca312f19c3c1b07e50376b318ce6a969d7

**Comment by orbea** [comment]
@hyarsan Thanks, I tried to look at yours, but the link didn't work here...

**Pull request merged**
