### PR TITLE
LibRetro core

### PR DESCRIPTION
**Pull request by fr500**
This is just a stub core, it builds correctly but it's still not hooked up.
Needs:

- Hook up retro_init, retro_load, retro_run, and friedns
- Workaround the sdl dependency

If noone picks it up I may hook it up the next weekend
https://github.com/drhelius/Gearboy/issues/52

### CODE REVIEW

**Comment by fr500** [comment]
**do-not-merge-this** it does nothing so far other than help anyone interested in porting

**Comment by fr500** [comment]
@drhelius we'd be more than pleased to have the core upstream, let us know if any changes are required for this purpose.

You don't have savestate support yet right? 

What we're missing so far:
- A way to read the SRAM/RTC data directly instead of relying on files to save/load (Ref: https://github.com/libretro/SameBoy/blob/master/libretro/libretro.c#L475)
- A way to read / write the whole RAM contents for savestates

Those are the main features. Other than that we could use a way to read / write specific memory areas to have retroachievement support but that's not crucial.

**Comment by drhelius** [comment]
Thanks for all the work. I was able to build it and test it on RetroArch today!

You can use it right now but I'm going to refactor the core anyway to avoid all those #ifdef and add support for RAM/RTC manipulation. That shouldn't take too long.

I'll merge this as soon as you're ready. You can later pull my changes at your will.

**Comment by fr500** [comment]
Hey

It's... pretty much ready right now, I think it would be better to merge now and then we can re-adapt to your changes!

Thanks for your support.
I think we're still doing something wrong with audio, maybe I need a way to read how long the sample buffer really is like we do on SameBoy.

**Comment by hyarsan** [comment]
It crashes when I close content and other things I remember.

**Pull request merged**
