### PR TITLE
sav extension is managed for loading

### PR DESCRIPTION
**Pull request by RyDroid**
Hi.

https://github.com/drhelius/Gearboy/issues/45
This time it is not cosmetic changes, it is a new "feature".

Regards.

### CODE REVIEW

**Comment by JBoughter** [comment]
I'm not sure if you automatically gain credit of that whole chunk of code for adding your code. Maybe put yours next to his?

**Comment by RyDroid** [comment]
I removed my credit.

**Comment by drhelius** [comment]
I'm refactoring the core so I'll be rewriting this myself, thanks.

**Comment by RyDroid** [comment]
Ok, good luck for this work.

**Pull request closed without merging**
