### PR TITLE
Proposal of Fix #124 and fix palette issue on Big Endian platforms

### LINKED ISSUE #124: Core not usable on PS3
Beetwen v3.0.4 and v3.1.0 was introduced an issue on PS3 that makes Gearboy non usable.
RPCS3 emulator send an not well identificated  `sys_memory_allocate' failed`.
Further investigation will be required.....

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by crystalct** [comment]
```
#if defined(IS_BIG_ENDIAN)
    u16 color = *palette_color_final;
    *palette_color_final = ((color << 8) & 0xFF00) | ((color >> 8) & 0x00FF);
#endif
```
Tested without it and it works correctly in both little and endian.

**Comment by drhelius** [comment]
Thanks for your effort. Would you mind if a I add more commits to your branch? I want to avoid conditional compilation with macros as much as possible.

Regarding the palette order, is it failing in big endian? or it has no effect?

**Comment by crystalct** [comment]
Surely previous `*palette_color_final` is already endian safe, so with swap bytes color become wrong in Big Endiam machine.
Add your commits... of course.

**Comment by drhelius** [comment]
Sorry for the delay, I happen to find the time today.
The allocation for debugger info is now dynamic and should only happen in desktop platforms.
If you can test it in a big endian machine I'll be very grateful.
Thanks for your help!

**Comment by crystalct** [comment]
Surely.

**Comment by crystalct** [comment]
image

image

**Pull request merged**
